- hosts: master
  become: yes
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: enable bash-completetion
      shell: echo "source <(kubectl completion bash)" >> /home/ubuntu/.bashrc
      args:
        chdir: $HOME

    - name: install Pod network
      become: yes
      become_user: ubuntu
      shell: |
        set -e
        curl -q https://docs.projectcalico.org/manifests/calico.yaml -o calico.yaml
        sed -i -e "s?192.168.0.0/16?10.244.0.0/16?g" calico.yaml
        kubectl apply -f calico.yaml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
